### ISSUE TITLE
Opt-out not working

### ISSUE THREAD

**Issue by sinedied** [brminnick/GitHubReadmeWebTrends#15]
I tried to opt-out today bug I got this error:
![Screenshot 2020-11-16 at 09 51 00](https://user-images.githubusercontent.com/593151/99231694-40a3a480-27f1-11eb-9102-dfd092cbd9fd.png)

I don't know if it's intended, but I received multiple PRs for the same repo, hence the need to opt-out to reduce the noise.
Thanks

**Comment by brminnick** [comment]
Hey Yohan! 

The multiple PRs were a bug that has been fixed and it won’t happen again. 

It’s too late to opt out of the November PRs because the tool triggered on Friday and is still combing through a backlog of GitHub repos.

By clicking Opt Out, you will be opted out of next month’s PRs. That being said, if you merge the PRs this month, you won’t get any PRs next month. 

The reason your Opt Out didn’t work is because you are not logged in using your Microsoft Alias. Ie, You logged as Yohan.Lasorsa@Microsoft.com instead of yolasors@microsoft.com. The tool is cross-referencing your Microsoft alias listed in the YAML file here: https://github.com/MicrosoftDocs/cloud-developer-advocates/blob/7586ccfbad7f0cc26b290626c7b50a2c3240c4ab/advocates/yohan-lasorsa.yml#L7

**Comment by manekinekko** [comment]
Hi, I am getting the same behaviour. I use `wassim.chegham@` to log into all the different MS service, and rarely use my alias.

**Comment by brminnick** [comment]
@sinedied @manekinekko Can you try the Opt-Out Website, using your full-name email address login, e.g.  Yohan.Lasorsa@Microsoft.com not yolasors@microsoft.com, again?

I just pushed an update to the website that may have fixed this bug, but I cannot test it because I cannot login with my full-name email address, brandon.minnick@microsoft.com.

**Comment by sinedied** [comment]
Just tried, seems to work now thanks :+1:

**Comment by brminnick** [comment]
Closed via https://github.com/brminnick/GitHubReadmeWebTrends/commit/4118bca2ff8f79395391e74177d76eb91580fbce
